# Generated by Django 5.2.12 on 2026-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicreation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_images/'),
        ),
    ]
