# Generated by Django 5.2.12 on 2026-04-04 08:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0003_aicreation_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicreation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
