# Generated by Django 5.2.12 on 2026-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0004_alter_aicreation_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicreation',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='aicreation',
            name='colab_link',
            field=models.URLField(blank=True, help_text='Link to Google Colab Notebook', null=True),
        ),
        migrations.AddField(
            model_name='aicreation',
            name='github_link',
            field=models.URLField(blank=True, help_text='Link to GitHub Repository', null=True),
        ),
        migrations.AddField(
            model_name='aicreation',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly title', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aicreation',
            name='status',
            field=models.CharField(choices=[('concept', 'Concept / Idea'), ('training', 'Training Model'), ('testing', 'Testing & Evaluation'), ('completed', 'Completed'), ('deployed', 'Deployed / Live')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='aicreation',
            name='summary',
            field=models.CharField(blank=True, help_text='Short description for the list view', max_length=255),
        ),
        migrations.AddField(
            model_name='aicreation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
