# Generated by Django 5.2.12 on 2026-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projectcategory_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
